# CMake generated Testfile for 
# Source directory: /mnt/c/users/alex/desktop/open_spiel/open_spiel/games
# Build directory: /mnt/c/users/alex/desktop/open_spiel/open_spiel/examples/games
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(2048_test "2048_test")
set_tests_properties(2048_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;285;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(amazons_test "amazons_test")
set_tests_properties(amazons_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;289;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(backgammon_test "backgammon_test")
set_tests_properties(backgammon_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;293;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(bargaining_test "bargaining_test")
set_tests_properties(bargaining_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;299;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(battleship_test "battleship_test")
set_tests_properties(battleship_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;303;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(blackjack_test "blackjack_test")
set_tests_properties(blackjack_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;307;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(blotto_test "blotto_test")
set_tests_properties(blotto_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;311;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(breakthrough_test "breakthrough_test")
set_tests_properties(breakthrough_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;315;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(bridge_test "bridge_test")
set_tests_properties(bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;319;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(catch_test "catch_test")
set_tests_properties(catch_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;323;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(checkers_test "checkers_test")
set_tests_properties(checkers_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;327;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(chess_test "chess_test")
set_tests_properties(chess_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;331;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(cliff_walking_test "cliff_walking_test")
set_tests_properties(cliff_walking_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;335;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(clobber_test "clobber_test")
set_tests_properties(clobber_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;339;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coin_game_test "coin_game_test")
set_tests_properties(coin_game_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;344;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(colored_trails_test "colored_trails_test")
set_tests_properties(colored_trails_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;352;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(connect_four_test "connect_four_test")
set_tests_properties(connect_four_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;357;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coop_box_pushing_test "coop_box_pushing_test")
set_tests_properties(coop_box_pushing_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;362;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(coordinated_mp_test "coordinated_mp_test")
set_tests_properties(coordinated_mp_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;367;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crazy_eights_test "crazy_eights_test")
set_tests_properties(crazy_eights_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;371;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crowd_modelling_test "crowd_modelling_test")
set_tests_properties(crowd_modelling_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;375;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(crowd_modelling_2d_test "crowd_modelling_2d_test")
set_tests_properties(crowd_modelling_2d_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;379;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(cursor_go_test "cursor_go_test")
set_tests_properties(cursor_go_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;384;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dark_chess_test "dark_chess_test")
set_tests_properties(dark_chess_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;388;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dark_hex_test "dark_hex_test")
set_tests_properties(dark_hex_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;392;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(deep_sea_test "deep_sea_test")
set_tests_properties(deep_sea_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;396;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dots_and_boxes_test "dots_and_boxes_test")
set_tests_properties(dots_and_boxes_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;400;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_data_test "dynamic_routing_data_test")
set_tests_properties(dynamic_routing_data_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;404;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_test "dynamic_routing_test")
set_tests_properties(dynamic_routing_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;408;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dynamic_routing_utils_test "dynamic_routing_utils_test")
set_tests_properties(dynamic_routing_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;412;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dou_dizhu_test "dou_dizhu_test")
set_tests_properties(dou_dizhu_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;416;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(dou_dizhu_utils_test "dou_dizhu_utils_test")
set_tests_properties(dou_dizhu_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;420;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(efg_game_test "efg_game_test")
set_tests_properties(efg_game_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;424;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(euchre_test "euchre_test")
set_tests_properties(euchre_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;428;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(first_sealed_auction_test "first_sealed_auction_test")
set_tests_properties(first_sealed_auction_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;433;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(garnet_test "garnet_test")
set_tests_properties(garnet_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;437;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(gin_rummy_test "gin_rummy_test")
set_tests_properties(gin_rummy_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;441;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(go_test "go_test")
set_tests_properties(go_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;445;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(phantom_go_test "phantom_go_test")
set_tests_properties(phantom_go_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;449;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(goofspiel_test "goofspiel_test")
set_tests_properties(goofspiel_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;453;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(havannah_test "havannah_test")
set_tests_properties(havannah_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;457;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(hearts_test "hearts_test")
set_tests_properties(hearts_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;461;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(hex_test "hex_test")
set_tests_properties(hex_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;465;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(kriegspiel_test "kriegspiel_test")
set_tests_properties(kriegspiel_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;469;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(kuhn_poker_test "kuhn_poker_test")
set_tests_properties(kuhn_poker_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;474;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(leduc_poker_test "leduc_poker_test")
set_tests_properties(leduc_poker_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;479;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(lewis_signaling_test "lewis_signaling_test")
set_tests_properties(lewis_signaling_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;483;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(liars_dice_test "liars_dice_test")
set_tests_properties(liars_dice_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;488;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(maedn_test "maedn_test")
set_tests_properties(maedn_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;492;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(magic_the_gathering_test "magic_the_gathering_test")
set_tests_properties(magic_the_gathering_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;496;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(mancala_test "mancala_test")
set_tests_properties(mancala_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;500;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(markov_soccer_test "markov_soccer_test")
set_tests_properties(markov_soccer_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;505;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(matching_pennies_3p_test "matching_pennies_3p_test")
set_tests_properties(matching_pennies_3p_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;511;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(matrix_games_test "matrix_games_test")
set_tests_properties(matrix_games_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;515;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(morpion_solitaire_test "morpion_solitaire_test")
set_tests_properties(morpion_solitaire_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;519;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(negotiation_test "negotiation_test")
set_tests_properties(negotiation_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;524;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nfg_game_test "nfg_game_test")
set_tests_properties(nfg_game_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;529;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nim_test "nim_test")
set_tests_properties(nim_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;533;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(nine_mens_morris_test "nine_mens_morris_test")
set_tests_properties(nine_mens_morris_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;537;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oh_hell_test "oh_hell_test")
set_tests_properties(oh_hell_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;541;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oshi_zumo_test "oshi_zumo_test")
set_tests_properties(oshi_zumo_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;546;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(othello_test "othello_test")
set_tests_properties(othello_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;550;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(oware_test "oware_test")
set_tests_properties(oware_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;555;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pathfinding_test "pathfinding_test")
set_tests_properties(pathfinding_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;559;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pentago_test "pentago_test")
set_tests_properties(pentago_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;563;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(phantom_ttt_test "phantom_ttt_test")
set_tests_properties(phantom_ttt_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;567;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(pig_test "pig_test")
set_tests_properties(pig_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;571;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(quoridor_test "quoridor_test")
set_tests_properties(quoridor_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;575;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(rbc_test "rbc_test")
set_tests_properties(rbc_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;579;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(sheriff_test "sheriff_test")
set_tests_properties(sheriff_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;583;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(skat_test "skat_test")
set_tests_properties(skat_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;587;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(solitaire_test "solitaire_test")
set_tests_properties(solitaire_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;591;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(spades_test "spades_test")
set_tests_properties(spades_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;595;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(stones_and_gems_test "stones_and_gems_test")
set_tests_properties(stones_and_gems_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;600;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tarok_test "tarok_test")
set_tests_properties(tarok_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;604;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tic_tac_toe_test "tic_tac_toe_test")
set_tests_properties(tic_tac_toe_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;608;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(laser_tag_test "laser_tag_test")
set_tests_properties(laser_tag_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;612;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tiny_bridge_test "tiny_bridge_test")
set_tests_properties(tiny_bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;617;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(tiny_hanabi_test "tiny_hanabi_test")
set_tests_properties(tiny_hanabi_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;622;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(trade_comm_test "trade_comm_test")
set_tests_properties(trade_comm_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;626;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(twixt_test "twixt_test")
set_tests_properties(twixt_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;630;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(ultimate_tic_tac_toe_test "ultimate_tic_tac_toe_test")
set_tests_properties(ultimate_tic_tac_toe_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;634;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
add_test(y_test "y_test")
set_tests_properties(y_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;646;add_test;/mnt/c/users/alex/desktop/open_spiel/open_spiel/games/CMakeLists.txt;0;")
